use Mix.Config

# query_args = ["SET search_path TO connection_prefix", []]
# Configure your database

#local database
config :support_service, SupportService.Repo,
  username: "postgres",
  password: "motaz2712",
  database: "SupportDB",
  hostname: "localhost",
  port: 5432,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  # after_connect: {Postgrex, :query!, query_args},
  ssl: false

# digitalocean database dev
# config :support_service, SupportService.Repo,
#   username: "doadmin",
#   password: "929G89DVkXkadMe6",
#   database: "SupportDB",
#   hostname: "db-postgresql-ams3-do-user-8500484-0.b.db.ondigitalocean.com",
#   port: 25060,
#   show_sensitive_data_on_connection_error: true,
#   pool_size: 10,
#   # after_connect: {Postgrex, :query!, query_args},
#   ssl: true




# gigalixir database dev
# config :support_service, SupportService.Repo,
#   username: "3a32e263-89d1-4b17-a0c0-560bb4eafafd-user",
#   password: "pw-aa3a33d5-2d37-4e94-a2d8-74e38da335b6",
#   database: "3a32e263-89d1-4b17-a0c0-560bb4eafafd",
#   hostname: "postgres-free-tier-v2020.gigalixir.com",
#   port: 5432,
#   show_sensitive_data_on_connection_error: true,
#   pool_size: 1,
#   # after_connect: {Postgrex, :query!, query_args},
#   ssl: false

# config :support_service, SupportService.Repo,
#   username: "doadmin",
#   password: "n86l04ublg1sn4bc",
#   database: "SupportDB",
#   hostname: "db-postgresql-ams3-do-user-8500484-0.b.db.ondigitalocean.com",
#   port: 25060,
#   show_sensitive_data_on_connection_error: true,
#   pool_size: 10,
#   # after_connect: {Postgrex, :query!, query_args},
#   ssl: true



  config :joken, default_signer: "AionSecretKeyForSenderSupport"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :support_service, SupportServiceWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :support_service, SupportServiceWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/support_service_web/(live|views)/.*(ex)$",
      ~r"lib/support_service_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
