INSERT INTO dbo.status_types (id, type, arabic_type, inserted_at, updated_at) VALUES (1, 'New', 'جديد', null, null);
INSERT INTO dbo.status_types (id, type, arabic_type, inserted_at, updated_at) VALUES (2, 'Ready', null, null, null);
INSERT INTO dbo.status_types (id, type, arabic_type, inserted_at, updated_at) VALUES (3, 'Working', null, null, null);
INSERT INTO dbo.status_types (id, type, arabic_type, inserted_at, updated_at) VALUES (4, 'Progress ', null, null, null);
INSERT INTO dbo.status_types (id, type, arabic_type, inserted_at, updated_at) VALUES (5, 'Suspended', null, null, null);
INSERT INTO dbo.status_types (id, type, arabic_type, inserted_at, updated_at) VALUES (6, 'Stopped', null, null, null);
INSERT INTO dbo.status_types (id, type, arabic_type, inserted_at, updated_at) VALUES (7, 'Reviewing', null, null, null);
INSERT INTO dbo.status_types (id, type, arabic_type, inserted_at, updated_at) VALUES (8, 'Penalty', null, null, null);
INSERT INTO dbo.status_types (id, type, arabic_type, inserted_at, updated_at) VALUES (9, 'Incomplete', null, null, null);
INSERT INTO dbo.status_types (id, type, arabic_type, inserted_at, updated_at) VALUES (10, 'Complete', null, null, null);
INSERT INTO dbo.status_types (id, type, arabic_type, inserted_at, updated_at) VALUES (11, 'Active', null, null, null);
INSERT INTO dbo.status_types (id, type, arabic_type, inserted_at, updated_at) VALUES (12, 'Inactive', null, null, null);